language: rust
rust:
  - stable
  - nightly
os:
  - linux
  - osx
  - windows
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
install:
  - rustup target add wasm32-unknown-unknown
  - rustup target add armv7-unknown-linux-gnueabihf
script:
  - cargo build
  - cargo build --target wasm32-unknown-unknown
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        cargo build --target armv7-unknown-linux-gnueabihf
    fi