language: rust
rust:
  - stable
  - nightly
os:
  - linux
  - osx
  - windows
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
install:
  - rustup target add wasm32-unknown-unknown
script:
  - cargo build
  - cargo build --target wasm32-unknown-unknown