language: rust
rust:
  - stable
  - nightly
os:
  - linux
  - osx
  - windows
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
install:
  - rustup target add wasm32-unknown-unknown
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libsdl2-dev; fi

script:
  - cargo build