[package]
name = "emerald"
version = "0.1.0"
authors = ["Bombfuse <eiffeldud@gmail.com>"]
edition = "2018"
description = "A lite, fully featured 2D game engine."
repository = "https://github.com/Bombfuse/emerald"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# Nightly
miniquad = { git = "https://github.com/not-fl3/miniquad", branch = "master" }
quad-snd = { git = "https://github.com/Bombfuse/quad-snd", branch = "master" }
miniquad_text_fontdue = { git = "https://github.com/Bombfuse/miniquad_text_fontdue", branch = "master" }
nanoserde = { git = "https://github.com/not-fl3/nanoserde", branch = "master" }
paintbrush = { git = "https://github.com/Bombfuse/paintbrush", branch = "master" }
rapier2d = { git = "https://github.com/dimforge/rapier", branch = "master", default-features = false, features = [ "dim2" ] }
hecs = { git = "https://github.com/Ralith/hecs", branch = "master" }

# Dependencies
instant = { version = "0.1.5", features = [ "now" ] }
image = "0.23.8"
glam = "0.9.3"
log = "0.4.11"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_log = { version = "0.2.0" }

[lib]
name = "emerald"
path = "src/lib.rs"

[[example]]
name = "hello_world"
path = "examples/hello_world/main.rs"

[[example]]
name = "bunnymark"

[[example]]
name = "sprite"

[[example]]
name = "color_rect"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-none-linux-gnueabihf-gcc"
