[package]
name = "emerald"
version = "0.1.1"
authors = ["Bombfuse <eiffeldud@gmail.com>"]
edition = "2018"
description = "A lite, fully featured 2D game engine."
repository = "https://github.com/Bombfuse/emerald"
license = "MIT OR Apache-2.0"

[features]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
logging = []
headless = []

[dependencies]
# Nightly
quad-snd = { git = "https://github.com/not-fl3/quad-snd", branch = "master" }

# Dependencies
image = { version = "0.23.10", default-features = false, features = [ "png" ] }
glam = "0.10.2"
log = "0.4.11"
quad-rand = "0.1.1"
gamepad = "0.1.1"
rapier2d = { version = "0.3.2", default-features = false, features = [ "dim2" ] }
fontdue = "0.4.0"
nanoserde = "0.1.20"
hecs = { version = "0.3.1", default-features = false }
miniquad = "0.3.0-alpha.22"

[lib]
name = "emerald"
path = "src/lib.rs"
