[package]
name = "emerald"
version = "0.1.0"
authors = ["Bombfuse <eiffeldud@gmail.com>"]
edition = "2018"
description = "A lite, fully featured 2D game engine."
repository = "https://github.com/atkostudios/emerald"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniquad = { git = "https://github.com/not-fl3/miniquad", branch = "master" }
paintbrush = { git = "https://github.com/Bombfuse/paintbrush", branch = "master" }
gilrs = "0.7.4"
quad-gl = "0.1.3"

[lib]
name = "emerald"
path = "src/lib.rs"

[[example]]
name = "hello_world"
path = "examples/hello_world/main.rs"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-none-linux-gnueabihf-gcc"