[package]
name = "emerald"
version = "0.1.0"
authors = ["Bombfuse <eiffeldud@gmail.com>"]
edition = "2018"
description = "A lite, fully featured 2D game engine."
repository = "https://github.com/atkostudios/emerald"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# Nightly dependencies
miniquad = { git = "https://github.com/not-fl3/miniquad", branch = "master" }
paintbrush = { git = "https://github.com/Bombfuse/paintbrush", branch = "master" }
fontdue = { git = "https://github.com/mooman219/fontdue", branch = "master" }

# Dependencies
instant = { version = "0.1.5", features = [ "now" ] }
nphysics2d = {version = "0.15.0", default-features = false, features = ["dim2"] }
image = "0.23.4"
legion = { version = "0.2.1", default-features = false }
glam = "0.8.7"

[lib]
name = "emerald"
path = "src/lib.rs"

[[example]]
name = "hello_world"
path = "examples/hello_world/main.rs"

[[example]]
name = "bunnymark"

[[example]]
name = "sprite"

[target.armv7-unknown-linux-gnueabihf]
linker = "arm-none-linux-gnueabihf-gcc"
