[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
editor = { path = "../editor" }
emd_desktop = { path = "../../runners/emd_desktop" } 
emerald = { path = "../../emerald" }